/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sample.ui;

import com.sample.DAO.HoaDonDichVuDAO;
import com.sample.model.HoaDonDichVu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akais
 */
public class FrHoaDonDV extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    List<HoaDonDichVu> list = new ArrayList<>();
    HoaDonDichVuDAO DAO_HDDV = new HoaDonDichVuDAO();

    public void loadToTableHDCT() {
        model = (DefaultTableModel) tbl_HDDV.getModel();
        model.setRowCount(0);
        try {
            list = DAO_HDDV.select();
            for (HoaDonDichVu hddv : list) {
                model.addRow(new Object[]{
                    hddv.getMaHDDV(),
                    hddv.getSuDung(),
                    hddv.getMaPhong(),
                    hddv.getTongTien(),
                    hddv.getTrangThai(),
                    hddv.getNguoiTao()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi đổ dữ liệu vào bảng" + e);
            e.printStackTrace();
        }
    }

    public void loadToTableHDCTByMaPhong() {
        model = (DefaultTableModel) tbl_HDDV.getModel();
        model.setRowCount(0);
        try {
            List<HoaDonDichVu> listHDCT = DAO_HDDV.findMaHDDVByMaPhong(txt_maPhong.getText());
            for (HoaDonDichVu hddv : list) {
                model.addRow(new Object[]{
                    hddv.getMaHDDV(),
                    hddv.getSuDung(),
                    hddv.getMaPhong(),
                    hddv.getTongTien(),
                    hddv.getTrangThai(),
                    hddv.getNguoiTao()
                });
            }
            if (listHDCT.size() > 0) {
                JOptionPane.showMessageDialog(this, "Tìm thành công");
            } else {
                loadToTableHDCT();
                JOptionPane.showMessageDialog(this, "Không có thông tin mã phòng này");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi đổ dữ liệu vào bảng" + e);
            e.printStackTrace();
        }
    }

    public FrHoaDonDV() {
        initComponents();
        loadToTableHDCT();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_maPhong = new javax.swing.JTextField();
        btn_Tim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_HDDV = new javax.swing.JTable();

        setClosable(true);
        setTitle("HÓA ĐƠN DỊCH VỤ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tìm Hóa Đơn Dịch Vụ (Theo Phòng)"));

        btn_Tim.setText("Tìm");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_maPhong)
                .addGap(18, 18, 18)
                .addComponent(btn_Tim)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Tim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Tim, txt_maPhong});

        tbl_HDDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã HDDV", "Mã DV sử dụng", "Mã Phòng", "Tổng Tiền", "Trang Thái", "Người Tạo"
            }
        ));
        jScrollPane1.setViewportView(tbl_HDDV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        try {
            loadToTableHDCTByMaPhong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e);
        }
    }//GEN-LAST:event_btn_TimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Tim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_HDDV;
    private javax.swing.JTextField txt_maPhong;
    // End of variables declaration//GEN-END:variables
}
