/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sample.ui;

import com.sample.DAO.UserDAO;
import com.sample.model.User;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    List<User> listUser = new ArrayList<>();
    String roles = "";
    UserDAO userDAO = new UserDAO();
    String userName = "";
    String pass = "";

    public boolean checkNull() {
        userName = txt_TenDN.getText();
        pass = new String(ps_MatKhau.getPassword());
        if (userName.equals("")) {
            JOptionPane.showMessageDialog(this, "Không bỏ trống tên đăng nhập");
            return false;
        } else if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Không bỏ trống mật khẩu");
            return false;
        }
        return true;
    }

    public void login() {
        if (checkNull()) {
            userDAO.convertPassToString(userName);
            List<User> list = userDAO.selectLogin(userName, pass);
            if (userName.equalsIgnoreCase(list.get(0).getUser()) && pass.equalsIgnoreCase(list.get(0).getPassWord())) {
                roles = list.get(0).getRoles();
                userDAO.convertStringtoPass(userName);
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!!");
                if (roles.equalsIgnoreCase("NV")) {
                    new FrMain(userName, roles).setVisible(true);

                } else if (roles.equalsIgnoreCase("CN")) {
                    new FrMain(userName, roles).setVisible(true);
                }
            }
        }
    }

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_HinhIcon = new javax.swing.JLabel();
        pnl_Form = new javax.swing.JPanel();
        lbl_DangNhap = new javax.swing.JLabel();
        lbl_TenDN = new javax.swing.JLabel();
        txt_TenDN = new javax.swing.JTextField();
        lbl_MatKhau = new javax.swing.JLabel();
        ps_MatKhau = new javax.swing.JPasswordField();
        btn_DangNhap = new javax.swing.JButton();
        btn_KetThuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ NHÀ TRỌ");

        lbl_HinhIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sample/icon/security.png"))); // NOI18N
        getContentPane().add(lbl_HinhIcon, java.awt.BorderLayout.LINE_START);

        lbl_DangNhap.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        lbl_DangNhap.setForeground(new java.awt.Color(0, 0, 153));
        lbl_DangNhap.setText("ĐĂNG NHẬP");

        lbl_TenDN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_TenDN.setText("Tên đăng nhập");

        lbl_MatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_MatKhau.setText("Mật khẩu");

        btn_DangNhap.setText("Đăng nhập");
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        btn_KetThuc.setText("Kết thúc");
        btn_KetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KetThucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_FormLayout = new javax.swing.GroupLayout(pnl_Form);
        pnl_Form.setLayout(pnl_FormLayout);
        pnl_FormLayout.setHorizontalGroup(
            pnl_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_DangNhap)
                        .addComponent(lbl_TenDN)
                        .addComponent(txt_TenDN)
                        .addComponent(lbl_MatKhau)
                        .addComponent(ps_MatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                    .addGroup(pnl_FormLayout.createSequentialGroup()
                        .addComponent(btn_DangNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btn_KetThuc)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnl_FormLayout.setVerticalGroup(
            pnl_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_DangNhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_TenDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_MatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ps_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnl_FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DangNhap)
                    .addComponent(btn_KetThuc))
                .addContainerGap())
        );

        getContentPane().add(pnl_Form, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        try {
            this.login();
            this.dispose();
        } catch (Exception e) {
            userDAO.convertStringtoPass(userName);
            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc password!!");
        }
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void btn_KetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KetThucActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_KetThucActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangNhap;
    private javax.swing.JButton btn_KetThuc;
    private javax.swing.JLabel lbl_DangNhap;
    private javax.swing.JLabel lbl_HinhIcon;
    private javax.swing.JLabel lbl_MatKhau;
    private javax.swing.JLabel lbl_TenDN;
    private javax.swing.JPanel pnl_Form;
    private javax.swing.JPasswordField ps_MatKhau;
    private javax.swing.JTextField txt_TenDN;
    // End of variables declaration//GEN-END:variables
}
